Repository AfnwTeam/AfnwCore2, pull requests merged in 2022-01, with the labels that each got.

#3 コードスキャンリングの追加
  .github/workflows/codeql-analysis.yml
Labels: Type: building

#4 Afnw lobby features
  pom.xml
  src/main/java/net/azisaba/afnw/afnwcore2/AfnwCore2.java
  src/main/java/net/azisaba/afnw/afnwcore2/commands/LobbyCommand.java
  src/main/java/net/azisaba/afnw/afnwcore2/listener/AFKTeleporter.java
  src/main/java/net/azisaba/afnw/afnwcore2/listener/Lobby.java
  src/main/java/net/azisaba/afnw/afnwcore2/listener/PlayerJoinQuitEvent.java
  src/main/resources/plugin.yml
Labels: Type: elements and features, Version: v1.17.1, Type: improvement

#11 /voteが使えない問題の修正
  pom.xml
  src/main/java/net/azisaba/afnw/afnwcore2/AfnwCore2.java
  src/main/java/net/azisaba/afnw/afnwcore2/commands/TicketCommand.java
  src/main/resources/plugin.yml
Labels: Type: bug, Category: Other

#12 Add vote block
  src/main/java/net/azisaba/afnw/afnwcore2/AfnwCore2.java
  src/main/java/net/azisaba/afnw/afnwcore2/commands/LobbyCommand.java
  src/main/java/net/azisaba/afnw/afnwcore2/listener/Lobby.java
  src/main/resources/plugin.yml
Labels: Type: elements and features, Category: Other

#15 [CHANGE] execute setvoteurlblock on plugin load
  src/main/java/net/azisaba/afnw/afnwcore2/AfnwCore2.java
  src/main/java/net/azisaba/afnw/afnwcore2/commands/LobbyCommand.java
  src/main/java/net/azisaba/afnw/afnwcore2/listener/Lobby.java
  src/main/resources/config.yml
Labels: Category: Voting System, Type: improvement
