Repository AfnwTeam/AfnwCore2, pull requests merged in 2022-05, with the labels that each got.

#5 feat: RespawnCommandの追加
  src/main/java/net/azisaba/afnw/afnwcore2/AfnwCore2.java
  src/main/java/net/azisaba/afnw/afnwcore2/commands/AfnwCommand.java
  src/main/java/net/azisaba/afnw/afnwcore2/commands/RespawnCommand.java
  src/main/java/net/azisaba/afnw/afnwcore2/commands/VoteCommand.java
  src/main/resources/plugin.yml
Labels: Type: elements and feature

#11 chore: アジ鯖のrenovateの設定を使用するように
  .github/renovate.json
  renovate.json
Labels: dependency

#14 feat: 死亡メッセージの追加
  build.gradle
  src/main/java/net/azisaba/afnw/afnwcore2/AfnwCore2.java
  src/main/java/net/azisaba/afnw/afnwcore2/listeners/player/DeathListener.java
Labels: Type: elements and feature

#15 feat: チケットシステムの完成
  src/main/java/net/azisaba/afnw/afnwcore2/AfnwCore2.java
  src/main/java/net/azisaba/afnw/afnwcore2/commands/AfnwCommand.java
  src/main/java/net/azisaba/afnw/afnwcore2/commands/ConfigReloadCommand.java
  src/main/java/net/azisaba/afnw/afnwcore2/commands/TicketCommand.java
  src/main/resources/config.yml
  src/main/resources/plugin.yml
Labels: Type: elements and feature

#17 fix: 苗木保護機能・農作物保護機能の苗木保護bypassが正しく動作しない問題の修正
  build.gradle
  src/main/java/net/azisaba/afnw/afnwcore2/listeners/block/CropsBreakCanceller.java
  src/main/java/net/azisaba/afnw/afnwcore2/listeners/block/SaplingBreakCanceller.java
  src/main/resources/plugin.yml
Labels: Type: bug
